Develop
khushbuSatasiya/scrum-master-v2 pull request #11
Opened 2023-11-06 11:00 UTC by Yash-scaletech

Add WFH Section

2023-11-06 11:22 UTC, Daxesh3 requested changes

2023-11-06 11:22 UTC, Daxesh3 commented on src/features/wfh/component/wfh.tsx
> +					console.log('🚀 ~ file: wfh.tsx:52 ~ .then ~ res:', res.data.items);
remove logs

2023-11-06 11:22 UTC, Daxesh3 commented on src/features/wfh/component/wfh.tsx
> +	const [wfhList, setWfhList] = useState<[]>([]);
give proper type

2023-11-06 11:22 UTC, Daxesh3 commented on src/features/wfh/component/wfh.tsx
> +					isUpcomingWfh={true}
no need to write true

2023-11-06 11:22 UTC, Daxesh3 commented on src/shared/components/table/container/table.tsx
> +		return leave && !item[upcomingProperty] ? 'gray-background' : '';
use useMemo

2023-11-06 11:25 UTC, Yash-scaletech commented on src/features/wfh/component/wfh.tsx
> +					console.log('🚀 ~ file: wfh.tsx:52 ~ .then ~ res:', res.data.items);
Done

2023-11-06 11:26 UTC, Yash-scaletech commented on src/features/wfh/component/wfh.tsx
> +					isUpcomingWfh={true}
Done

2023-11-06 12:14 UTC, Yash-scaletech commented on src/features/wfh/component/wfh.tsx
> +	const [wfhList, setWfhList] = useState<[]>([]);
Done

2023-11-08 05:35 UTC, Yash-scaletech commented on src/shared/components/table/container/table.tsx
> +		return leave && !item[upcomingProperty] ? 'gray-background' : '';
Done

2023-11-08 06:12 UTC, Daxesh3 approved these changes

2023-11-08 06:12 UTC, merged